- name: Check Jira task in branch name
  set_fact:
    ci_jira_task: "{{ ci_jira_github_branch | regex_search(ci_jira_task_filter) }}"

- name: Found Jira task
  debug:
    msg: "{{ ci_jira_task }}"

- name: Get comments from Jira task {{ ci_jira_task }}
  uri:
    url: "{{ ci_jira_api }}/issue/{{ ci_jira_task }}/comment"
    method: GET
    user: '{{ ci_jira_username }}'
    password: '{{ ci_jira_password }}'
    force_basic_auth: yes
    status_code: 200
  register: ci_jira_task_comments
  ignore_errors: "{{ ci_jira_ignore_errors }}"
  when:
  - ci_jira_api | length > 0
  - ci_jira_task | length > 0

- name: Find Jira comment id
  set_fact:
    ci_jira_task_comment_id: "{{ ci_jira_task_comments.json.comments[-1].id }}"
  when:
  - ci_jira_api | length > 0
  - ci_jira_task | length > 0
  - ci_jira_task_comments is succeeded
  - (ci_jira_task_comments.json.comments | default([])) | length > 0
  - ci_jira_message_title in ci_jira_task_comments.json.comments[-1].body
  - ci_jira_message_body_default in ci_jira_task_comments.json.comments[-1].body

- name: Set message
  set_fact:
    ci_jira_message: |
      {{ ci_jira_message_wrapper_begin }}
      {% if ci_jira_github_pr | length > 0 and ci_jira_github_repository_url | length > 0 %}{{ ci_jira_message_body_default }}{% endif %}
      {{ ci_jira_message_body }}
      {{ ci_jira_message_wrapper_end }}
  when:
  - ci_jira_api | length > 0
  - ci_jira_task | length > 0
  - ci_jira_task_comments is succeeded

- name: Replace message in comment
  set_fact:
    ci_jira_message: "{{ ci_jira_task_comments.json.comments[-1].body | regex_replace(ci_jira_message_mask, ci_jira_message) }}"
  when:
  - ci_jira_task_comments is succeeded
  - ci_jira_task_comment_id is defined
  - ci_jira_task_comments.json.comments[-1].body is search(ci_jira_message_mask)

- name: Add message to comment
  set_fact:
    ci_jira_message: |
      {{ ci_jira_task_comments.json.comments[-1].body }}
      {{ ci_jira_message }}
  when:
  - ci_jira_task_comments is succeeded
  - ci_jira_task_comment_id is defined
  - ci_jira_task_comments.json.comments[-1].body is not search(ci_jira_message_mask)

- name: Add comment to Jira task {{ ci_jira_task }}
  uri:
    url: "{{ ci_jira_api }}/issue/{{ ci_jira_task }}/comment"
    method: POST
    body:
      body: "{{ ci_jira_message }}"
    body_format: json
    user: '{{ ci_jira_username }}'
    password: '{{ ci_jira_password }}'
    force_basic_auth: yes
    status_code: 201
  when:
  - ci_jira_api | length > 0
  - ci_jira_task | length > 0
  - ci_jira_task_comments is succeeded
  - ci_jira_task_comment_id is not defined

- name: Update comment in Jira task {{ ci_jira_task }}
  uri:
    url: "{{ ci_jira_api }}/issue/{{ ci_jira_task }}/comment/{{ ci_jira_task_comment_id }}"
    method: PUT
    body:
      body: "{{ ci_jira_message }}"
    body_format: json
    user: '{{ ci_jira_username }}'
    password: '{{ ci_jira_password }}'
    force_basic_auth: yes
    status_code: 200
  when:
  - ci_jira_task_comments is succeeded
  - ci_jira_task_comment_id is defined
